steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build container image'
  env:
  - 'DOCKER_BUILDKIT=1'
  args: [
    'build',
    '.',
    '-t',
    'europe-west1-docker.pkg.dev/$PROJECT_ID/project-registry/project-image',
    '-f',
    'Dockerfile'
  ]
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push container image'
  args: [
    'push',
    'europe-west1-docker.pkg.dev/$PROJECT_ID/project-registry/project-image'
  ]
  
options:
  logging: CLOUD_LOGGING_ONLY